### ISSUE TITLE
get cellset timestamps

### ISSUE THREAD

**Issue by bendichter** [inscopix/py_isx#45]
I'm not sure if this is a duplicate of #13, but what is the recommended way to get the frame times from a cellset file?

**Comment by sg-s** [comment]
it is a dupe -- this hasn't been implemented yet.

**Comment by bendichter** [comment]
OK. This is currently blocking for us to support NWB conversion for Inscopix files.

**Comment by bendichter** [comment]
Not blocking. We can use `1 / cell_set.timing.period.secs_float`.
